### PR TITLE
Bump NPM dependencies

### PR DESCRIPTION
**Pull request by davidhorak**
# Description
- Bump NPM dependencies

### Test Coverage
- [x] unit

### CODE REVIEW

**Comment by luiz290788** [comment]
Quick question about bumping dependencies on libraries, do we release a new version after bumping the dependencies? should we?

**Comment by davidhorak** [comment]
> Quick question about bumping dependencies on libraries, do we release a new version after bumping the dependencies? should we?

Not currently but it may be a nice best practice to do so ... ideally in automated manner. Thoughts?

**Comment by luiz290788** [comment]
> > Quick question about bumping dependencies on libraries, do we release a new version after bumping the dependencies? should we?
> 
> Not currently but it may be a nice best practice to do so ... ideally in automated manner.
> These could be considered as minor version updates, therefore not requiring any changelog update.
> 
> Thoughts?

I like that, because the consumers of this library only benefit from the dependency updates when we release a new version. Maybe have a cadence for doing that, once a month we release updates that are only dependency update.

**Comment by davidhorak** [comment]
> I like that, because the consumers of this library only benefit from the dependency updates when we release a new version. Maybe have a cadence for doing that, once a month we release updates that are only dependency update.

Agree, will create a housekeeping ticket for it!

**Review by lilyvanoekel — APPROVED** [review]

**Pull request merged**
